name: CI
on:
  push:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

jobs:
  # test-sdk-archetype:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       archetype: ['cf-spring', 'cf-tomee', 'neo-javaee7']
  #       java: [ '8', '11' ]
  #   steps:
  #     - name: Setup java
  #       uses: joschi/setup-jdk@v2
  #       with:
  #         java-version: ${{ matrix.java }}
  #         architecture: x64
  #     - run: mvn -v
  #     - name: Generate test project
  #       run: |
  #         mvn archetype:generate -B -DarchetypeGroupId=com.sap.cloud.sdk.archetypes -DgroupId=mydemo -DartifactId=cloud-sdk-${{ matrix.archetype }}-archetype -DskipUsageAnalytics=true -Dversion=1.0 -DarchetypeArtifactId=scp-${{ matrix.archetype }} -DarchetypeVersion=LATEST
  #         cp -r cloud-sdk-${{ matrix.archetype }}-archetype/* .
  #         rm -rf cloud-sdk-${{ matrix.archetype }}-archetype
  #     - name: mavenBuild
  #       uses: SAP/project-piper-action@master
  #       with:
  #         command: mavenBuild
  #         piper-version: master
  #     - name: mavenExecuteStaticCodeChecks
  #       uses: SAP/project-piper-action@master
  #       with:
  #         command: mavenExecuteStaticCodeChecks
  #         piper-version: master
  #     - name: Notify on failure
  #       if: failure()
  #       env:
  #         WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  #         MESSAGE: "Piper canary test for sdk archetype ${{ matrix.archetype }} on java ${{ matrix.java }} failed, see https://github.com/SAP/jenkins-library-test/actions for details."
  #         CHANNEL: ${{ secrets.CHANNEL }}
  #         ICON: ${{ secrets.ICON }}
  #         USERNAME: Testing Bot
  #       uses: svikramjeet/git-actions@master
  #     - uses: 'actions/upload-artifact@v2'
  #       with:
  #           name: workspace ${{ matrix.archetype }} ${{ matrix.java }}
  #           path: ${{ github.workspace }}

  test-sdk-mta:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        archetype: ['cf-spring', 'cf-tomee']
        java: [ '8', '11' ]
    steps:
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: mvn -v
      - name: Generate test project
        run: |
          mvn archetype:generate -B -DarchetypeGroupId=com.sap.cloud.sdk.archetypes -DgroupId=mydemo -DartifactId=cloud-sdk-${{ matrix.archetype }}-archetype -DskipUsageAnalytics=true -Dversion=1.0 -DarchetypeArtifactId=scp-${{ matrix.archetype }} -DarchetypeVersion=LATEST
          cp -r cloud-sdk-${{ matrix.archetype }}-archetype/* .
          rm -rf cloud-sdk-${{ matrix.archetype }}-archetype
          wget https://gist.githubusercontent.com/fwilhe/0bc0848e9cc2487114c3c96060acbfc7/raw/2639331f9a1502c487000017f7b70db25b825ff6/mta-${{ matrix.archetype }}.yaml
          mv mta*yaml mta.yaml

      - run: find .

      - run: curl -L "https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.0.15/cloud-mta-build-tool_1.0.15_Linux_amd64.tar.gz" | sudo tar -zx -C /usr/local/bin

      - name: mtaBuild
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
          piper-version: master

  # nexus:
  #   runs-on: ubuntu-latest
  #   needs: test-sdk-archetype
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: workspace cf-tomee 8
  #         path: ${{ github.workspace }}
  #     - run: find .
  #     - run: docker run -d --name=nexus -p 8081:8081 -e NEXUS_SECURITY_RANDOMPASSWORD=false sonatype/nexus3:latest
  #     - run: until curl --fail http://localhost:8081/service/rest/v1/status; do sleep 5; done
  #     - name: Upload artifact to nexus
  #       uses: SAP/project-piper-action@master
  #       with:
  #         command: nexusUpload
  #         flags: '--user=admin --password=admin123 --mavenRepository=maven-releases --url=http://localhost:8081'
  #         piper-version: master
  #     - name: Check if uploaded artifact can be downloaded
  #       run: wget http://localhost:8081/repository/maven-releases/mydemo/cloud-sdk-cf-tomee-archetype-application/1.0/cloud-sdk-cf-tomee-archetype-application-1.0.war
  #     - name: Notify on failure
  #       if: failure()
  #       env:
  #         WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  #         MESSAGE: "Piper canary test for nexus upload failed, see https://github.com/SAP/jenkins-library-test/actions for details."
  #         CHANNEL: ${{ secrets.CHANNEL }}
  #         ICON: ${{ secrets.ICON }}
  #         USERNAME: Testing Bot
  #       uses: svikramjeet/git-actions@master
