name: CI
on:
  push:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

jobs:
  test-sdk-archetype:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        archetype: ['cf-spring', 'cf-tomee', 'neo-javaee7']
        java: [ '8', '11' ]
    steps:
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: mvn -v
      - name: Generate test project
        run: |
          mvn archetype:generate -B -DarchetypeGroupId=com.sap.cloud.sdk.archetypes -DgroupId=mydemo -DartifactId=cloud-sdk-${{ matrix.archetype }}-archetype -DskipUsageAnalytics=true -Dversion=1.0 -DarchetypeArtifactId=scp-${{ matrix.archetype }} -DarchetypeVersion=LATEST
          cp -r cloud-sdk-${{ matrix.archetype }}-archetype/* .
          rm -rf cloud-sdk-${{ matrix.archetype }}-archetype
      - name: mavenBuild
        uses: SAP/project-piper-action@master
        with:
          command: mavenBuild
          piper-version: kotlin-poc
      - name: mavenExecuteIntegration
        uses: SAP/project-piper-action@master
        with:
          command: mavenExecuteIntegration
          piper-version: kotlin-poc

      - name: mavenExecuteStaticCodeChecks
        uses: SAP/project-piper-action@master
        with:
          command: mavenExecuteStaticCodeChecks
          piper-version: kotlin-poc
 
