name: CI
on:
  push:
  workflow_dispatch:

jobs:
  test-sdk-archetype:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        archetype: ['cf-spring', 'cf-tomee', 'neo-javaee7']
        java: [ '8', '11' ]
    steps:
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: mvn -v
      - name: Generate test project
        run: |
          mvn archetype:generate -B -DarchetypeGroupId=com.sap.cloud.sdk.archetypes -DgroupId=mydemo -DartifactId=cloud-sdk-${{ matrix.archetype }}-archetype -DskipUsageAnalytics=true -Dversion=1.0 -DarchetypeArtifactId=scp-${{ matrix.archetype }} -DarchetypeVersion=LATEST
          cp -r cloud-sdk-${{ matrix.archetype }}-archetype/* .
          rm -rf cloud-sdk-${{ matrix.archetype }}-archetype
      - name: mavenBuild
        uses: SAP/project-piper-action@test
        with:
          command: mavenBuild
          piper-version: master
      - name: mavenExecuteIntegration
        uses: SAP/project-piper-action@test
        with:
          command: mavenExecuteIntegration
          piper-version: master

      - name: mavenExecuteStaticCodeChecks
        uses: SAP/project-piper-action@test
        with:
          command: mavenExecuteStaticCodeChecks
          piper-version: master
      - uses: 'actions/upload-artifact@v2'
        with:
            name: workspace ${{ matrix.archetype }} ${{ matrix.java }}
            path: ${{ github.workspace }}

  nexus:
    runs-on: ubuntu-latest
    needs: test-sdk-archetype
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: workspace cf-tomee 8
          path: ${{ github.workspace }}
      - run: find .
      - run: docker run -d --name=nexus -p 8081:8081 -e NEXUS_SECURITY_RANDOMPASSWORD=false sonatype/nexus3:3.21.1
      - run: until curl --fail http://localhost:8081/service/rest/v1/status; do sleep 5; done
      - name: Upload artifact to nexus
        uses: SAP/project-piper-action@test
        with:
          command: nexusUpload
          flags: '--username=admin --password=admin123 --mavenRepository=maven-releases --url=http://localhost:8081'
          piper-version: master
      - name: Check if uploaded artifact can be downloaded
        run: wget http://localhost:8081/repository/maven-releases/mydemo/cloud-sdk-cf-tomee-archetype-application/1.0/cloud-sdk-cf-tomee-archetype-application-1.0.war

